### PR TITLE
Decide on browsers

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
@winhamwr please help me decide on browsers.

I'm not sure which Safari versions we should support. I tend to go for only latest but if the tests pass then why not.

**Comment by mightyiam** [comment]
So, I think that I'll try to put in some more Android and iOS versions, perhaps, and see what happens.
As projects evolve, older versions will probably be dropped.

**Comment by mightyiam** [comment]
When I setup WYMeditor's Karma, I'll just remove the mobile browsers in that config file.

**Comment by winhamwr** [comment]
RE: safari, it [looks like](http://en.wikipedia.org/wiki/Safari_version_history) only 6.2+ is currently supported by Apple. The maximum we should support is that range, but I would be totally OK with only aiming for support of the latest version until someone with an older version of Safari files a bug.

**Comment by winhamwr** [comment]
Also, we can [drop IE7 support](https://policystat.zendesk.com/entries/53028619-Internet-Explorer-7-Sunset-Plans). Woohoo!

**Pull request merged**
